
// lib/seed-data.ts - FINAL CORRECTED VERSION (NO DUPLICATE IDs)
import { Types } from 'mongoose';

// Generate fixed ObjectIds for consistent seeding
const ids = {
  // Users
  adminId: new Types.ObjectId('507f1f77bcf86cd799439011'),
  userId: new Types.ObjectId('507f1f77bcf86cd799439012'),
  
  // Categories
  electronicsId: new Types.ObjectId('507f1f77bcf86cd799439021'),
  clothingId: new Types.ObjectId('507f1f77bcf86cd799439022'),
  homeId: new Types.ObjectId('507f1f77bcf86cd799439023'),
  booksId: new Types.ObjectId('507f1f77bcf86cd799439024'),
  sportsId: new Types.ObjectId('507f1f77bcf86cd799439025'),
  beautyId: new Types.ObjectId('507f1f77bcf86cd799439026'),
  toysId: new Types.ObjectId('507f1f77bcf86cd799439027'),
  foodId: new Types.ObjectId('507f1f77bcf86cd799439028'),
};

// USERS DATA (unchanged)
export const userSeeds = [
  {
    _id: ids.adminId,
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'admin123',
    role: 'ADMIN',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.userId,
    name: 'Regular User',
    email: 'user@example.com',
    password: 'user123',
    role: 'USER',
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=user',
    isActive: true,
    failedLoginAttempts: 0,
    lastLogin: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// CATEGORIES DATA (unchanged)
export const categorySeeds = [
  {
    _id: ids.electronicsId,
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest electronic gadgets and devices',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232260/photo-1498049794561-7780e7231661_ey3wzv.jpg',
    parent: null,
    productCount: 15,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.clothingId,
    name: 'Clothing',
    slug: 'clothing',
    description: 'Trendy clothing and fashion accessories',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232416/photo-1445205170230-053b83016050_itko7q.jpg',
    parent: null,
    productCount: 12,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.homeId,
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Home decor and kitchen essentials',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232676/photo-1556228453-efd6c1ff04f6_vbvrp6.jpg',
    parent: null,
    productCount: 10,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.booksId,
    name: 'Books',
    slug: 'books',
    description: 'Books, notebooks, and writing supplies',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232743/photo-1544947950-fa07a98d237f_zfjwxw.jpg',
    parent: null,
    productCount: 8,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.sportsId,
    name: 'Sports',
    slug: 'sports',
    description: 'Sports equipment and outdoor gear',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232794/photo-1461896836934-ffe607ba8211_zq3zl4.jpg',
    parent: null,
    productCount: 5,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.beautyId,
    name: 'Beauty',
    slug: 'beauty',
    description: 'Skincare, haircare, and personal grooming',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232854/photo-1596462502278-27bfdc403348_tvpmfr.jpg',
    parent: null,
    productCount: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.toysId,
    name: 'Toys',
    slug: 'toys',
    description: 'Fun toys and games for all ages',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775232905/photo-1550745165-9bc0b252726f_zmalgk.jpg',
    parent: null,
    productCount: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: ids.foodId,
    name: 'Food',
    slug: 'food',
    description: 'Gourmet food and premium beverages',
    image: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775237721/photo-1490818387583-1baba5e638af_qenz3c.jpg',
    parent: null,
    productCount: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// PRODUCTS DATA - UNIQUE IDs FOR EVERY PRODUCT
export const productSeeds = [
  // ---------- ELECTRONICS (5 products) ----------
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439031'),
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life.',
    shortDescription: 'Noise-cancelling wireless headphones',
    price: 199.99,
    category: ids.electronicsId,
    sku: 'ELEC-001',
    inventory: 150,
    status: 'ACTIVE',
    featured: true,
    tags: ['electronics', 'audio', 'wireless', 'headphones'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg',
      gallery: [
        'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg',
        'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg'
      ]
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439032'),
    name: 'Smart Watch Series 5',
    description: 'Advanced smartwatch with health monitoring, GPS, and LTE connectivity.',
    shortDescription: 'Advanced smartwatch with health tracking',
    price: 349.99,
    category: ids.electronicsId,
    sku: 'ELEC-002',
    inventory: 85,
    status: 'ACTIVE',
    featured: true,
    tags: ['electronics', 'wearable', 'smartwatch', 'fitness'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775285834/ivan-shilov-KiAYZZjpjkQ-unsplash_ign2b1.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775238092/seed-aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS_bez7jw_ktzasl.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439033'),
    name: '4K Ultra HD Smart TV',
    description: '55-inch 4K Ultra HD Smart TV with HDR and voice control.',
    shortDescription: '55-inch 4K Smart TV',
    price: 699.99,
    category: ids.electronicsId,
    sku: 'ELEC-003',
    inventory: 45,
    status: 'ACTIVE',
    featured: false,
    tags: ['electronics', 'tv', '4k', 'smart'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775277337/products/products/4k-ultra-hd-smart-tv-55-inch-main.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775277337/products/products/4k-ultra-hd-smart-tv-55-inch-main.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439034'),
    name: 'Gaming Laptop Pro',
    description: 'High-performance gaming laptop with RTX graphics, 16GB RAM, and 1TB SSD.',
    shortDescription: 'High-performance gaming laptop',
    price: 1499.99,
    category: ids.electronicsId,
    sku: 'ELEC-004',
    inventory: 25,
    status: 'ACTIVE',
    featured: true,
    tags: ['electronics', 'laptop', 'gaming', 'computer'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775277712/products/products/gaming-laptop-rtx-4060-main.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/v1775231630/seed-products/seed-aHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439035'),
    name: 'Wireless Earbuds Pro',
    description: 'True wireless earbuds with noise cancellation and wireless charging case.',
    shortDescription: 'True wireless noise-cancelling earbuds',
    price: 179.99,
    category: ids.electronicsId,
    sku: 'ELEC-005',
    inventory: 200,
    status: 'ACTIVE',
    featured: false,
    tags: ['electronics', 'earbuds', 'wireless', 'audio'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240218/daniel-romero-AgLMrojqjAM-unsplash_dmeinc.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ---------- CLOTHING (5 products) ----------
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439036'),
    name: 'Premium Cotton T-Shirt',
    description: '100% cotton t-shirt with a modern fit and comfortable feel.',
    shortDescription: 'Premium cotton t-shirt',
    price: 29.99,
    category: ids.clothingId,
    sku: 'CLOTH-001',
    inventory: 300,
    status: 'ACTIVE',
    featured: true,
    tags: ['clothing', 'tshirt', 'cotton', 'casual'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775277343/products/products/premium-cotton-t-shirt-thumb.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775277343/products/products/premium-cotton-t-shirt-thumb.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439037'),
    name: 'Denim Jacket',
    description: 'Classic denim jacket with a modern fit and distressed details.',
    shortDescription: 'Classic denim jacket',
    price: 79.99,
    category: ids.clothingId,
    sku: 'CLOTH-002',
    inventory: 85,
    status: 'ACTIVE',
    featured: true,
    tags: ['clothing', 'jacket', 'denim', 'outerwear'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240524/denim-jacket-isolated-on-white-nobody-trendy-fashion-denim-clothing-single-object_wxi1bb.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240524/denim-jacket-isolated-on-white-nobody-trendy-fashion-denim-clothing-single-object_wxi1bb.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439038'),
    name: 'Running Shoes',
    description: 'Lightweight running shoes with cushioning technology and breathable mesh.',
    shortDescription: 'Lightweight running shoes',
    price: 89.99,
    category: ids.clothingId,
    sku: 'CLOTH-003',
    inventory: 120,
    status: 'ACTIVE',
    featured: false,
    tags: ['clothing', 'shoes', 'running', 'athletic'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240754/usama-akram-kP6knT7tjn4-unsplash_cksgxv.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775240754/usama-akram-kP6knT7tjn4-unsplash_cksgxv.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439039'),
    name: 'Winter Parka',
    description: 'Waterproof winter parka with insulated lining and fur-trimmed hood.',
    shortDescription: 'Waterproof winter parka',
    price: 199.99,
    category: ids.clothingId,
    sku: 'CLOTH-004',
    inventory: 60,
    status: 'ACTIVE',
    featured: false,
    tags: ['clothing', 'winter', 'parka', 'coat'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775241109/oleg-ivanov-loEcRIcenT8-unsplash_ws2vhk.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775241109/oleg-ivanov-loEcRIcenT8-unsplash_ws2vhk.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId('507f1f77bcf86cd799439040'),
    name: 'Linen Button-Down Shirt',
    description: 'Breathable linen shirt with button-down collar and relaxed fit.',
    shortDescription: 'Breathable linen shirt',
    price: 59.99,
    category: ids.clothingId,
    sku: 'CLOTH-005',
    inventory: 95,
    status: 'ACTIVE',
    featured: false,
    tags: ['clothing', 'shirt', 'linen', 'summer'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775241314/tian-dayong-S4f4apZd-hA-unsplash_1_gplha3.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775241314/tian-dayong-S4f4apZd-hA-unsplash_1_gplha3.jpg',
      gallery: []
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ---------- HOME & KITCHEN (3 items – unique dynamic IDs) ----------
  {
    _id: new Types.ObjectId(), // unique ID
    name: 'Modern Wooden Chair',
    description: 'Ergonomic wooden chair for home and office.',
    shortDescription: 'Wooden chair',
    price: 149.99,
    category: ids.homeId,
    sku: 'HOME-101',
    inventory: 60,
    status: 'ACTIVE',
    featured: false,
    tags: ['home', 'furniture'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775312715/600_scfzep.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775312754/300_jdyzdc.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(), // unique ID
    name: 'Coffee Maker Machine',
    description: 'Brew perfect coffee every morning.',
    shortDescription: 'Coffee maker',
    price: 89.99,
    category: ids.homeId,
    sku: 'HOME-102',
    inventory: 70,
    status: 'ACTIVE',
    featured: true,
    tags: ['home', 'kitchen'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775314463/nathan-dumlao-xPSBoaJNs2g-unsplash_niofas.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775314463/nathan-dumlao-xPSBoaJNs2g-unsplash_niofas.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },


  // ---------- BOOKS (3 items – unique dynamic IDs) ----------
  {
    _id: new Types.ObjectId(),
    name: 'Atomic Habits',
    description: 'Proven strategies to build good habits and break bad ones.',
    shortDescription: 'Habits book',
    price: 19.99,
    category: ids.booksId,
    sku: 'BOOK-101',
    inventory: 200,
    status: 'ACTIVE',
    featured: true,
    tags: ['books', 'self-help'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775312944/600_ncjhfu.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313014/300_dp70ym.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    name: 'The Midnight Library',
    description: 'A novel about regrets and second chances.',
    shortDescription: 'Fiction novel',
    price: 24.99,
    category: ids.booksId,
    sku: 'BOOK-102',
    inventory: 150,
    status: 'ACTIVE',
    featured: false,
    tags: ['books', 'fiction'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313058/600_umrln6.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313113/300_ekc714.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth and happiness.',
    shortDescription: 'Finance book',
    price: 18.99,
    category: ids.booksId,
    sku: 'BOOK-103',
    inventory: 120,
    status: 'ACTIVE',
    featured: false,
    tags: ['books', 'finance'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313174/600_vqqr3y.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313217/300_knwkp0.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ---------- SPORTS (3 items – unique dynamic IDs) ----------
  {
    _id: new Types.ObjectId(),
    name: 'Professional Football',
    description: 'Size 5 durable football for matches.',
    shortDescription: 'Football',
    price: 29.99,
    category: ids.sportsId,
    sku: 'SPORT-101',
    inventory: 200,
    status: 'ACTIVE',
    featured: false,
    tags: ['sports', 'football'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313614/wesley-tingey-dKCKiC0BQtU-unsplash_xtmt4h.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313614/wesley-tingey-dKCKiC0BQtU-unsplash_xtmt4h.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    name: 'Yoga Mat Non-Slip',
    description: 'High density yoga mat with carrying strap.',
    shortDescription: 'Yoga mat',
    price: 39.99,
    category: ids.sportsId,
    sku: 'SPORT-102',
    inventory: 100,
    status: 'ACTIVE',
    featured: true,
    tags: ['sports', 'yoga'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313745/valentina-sotnikova-_1LgdHgyijY-unsplash_fgyyrp.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313745/valentina-sotnikova-_1LgdHgyijY-unsplash_fgyyrp.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: new Types.ObjectId(),
    name: 'Adjustable Dumbbell Set',
    description: '10kg – 40kg adjustable dumbbell set.',
    shortDescription: 'Dumbbell set',
    price: 199.99,
    category: ids.sportsId,
    sku: 'SPORT-103',
    inventory: 30,
    status: 'ACTIVE',
    featured: false,
    tags: ['sports', 'fitness'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313864/alex-saks-oJUo12AmHrM-unsplash_i7eqyl.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313864/alex-saks-oJUo12AmHrM-unsplash_i7eqyl.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // ---------- BEAUTY (3 items – unique dynamic IDs) ----------
  {
    _id: new Types.ObjectId(),
    name: 'Luxury Perfume for Men',
    description: 'Long‑lasting fragrance with premium notes.',
    shortDescription: 'Men perfume',
    price: 59.99,
    category: ids.beautyId,
    sku: 'BEAUTY-101',
    inventory: 110,
    status: 'ACTIVE',
    featured: true,
    tags: ['beauty', 'perfume'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313979/joe-calata-YuEAYjU4qZw-unsplash_xy1hae.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775313979/joe-calata-YuEAYjU4qZw-unsplash_xy1hae.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  
  {
    _id: new Types.ObjectId(),
    name: 'Hair Dryer Professional',
    description: 'Ionic hair dryer with fast drying.',
    shortDescription: 'Hair dryer',
    price: 79.99,
    category: ids.beautyId,
    sku: 'BEAUTY-103',
    inventory: 80,
    status: 'ACTIVE',
    featured: false,
    tags: ['beauty', 'haircare'],
    images: {
      main: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775314237/josh-marty-EsVjC6_8ERU-unsplash_dbdg4q.jpg',
      thumbnail: 'https://res.cloudinary.com/dgz6ixsno/image/upload/q_auto/f_auto/v1775314237/josh-marty-EsVjC6_8ERU-unsplash_dbdg4q.jpg',
      gallery: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];